<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <RootNamespace>DSE.Core</RootNamespace>
    <Version>1.1.0</Version>
    <Product>DSE</Product>
    <Company>finjackin</Company>
    <Authors>finjackin</Authors>
    <Copyright>Copyright (C) 2026 finjackin</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.1.0" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
    <PackageReference Include="Nefarius.Drivers.HidHide" Version="1.12.0" />
    <PackageReference Include="Nefarius.Utilities.DeviceManagement" Version="5.2.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

</Project>
